name: CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/ci.yaml"

  pull_request:
    branches:
      - main
      - develop
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/ci.yaml"

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-go-installation: true

  unit-tests:
    needs: lint

    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the tests
        run: go test ./... -v -race

  build:
    needs: unit-tests

    name: Build binary
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile
        run: go build main.go